export enum EventType {
    MANUFACTURED = 'MANUFACTURED',

    QUALITY_CHECKED = 'QUALITY_CHECKED',

    PACKAGED = 'PACKAGED',

    SHIPPED = 'SHIPPED',

    RECEIVED = 'RECEIVED',

    DISTRIBUTED = 'DISTRIBUTED',

    SOLD = 'SOLD',

    TEMPERATURE_MONITORED = 'TEMPERATURE_MONITORED',
}